# Generated by Django 3.2.5 on 2021-07-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='disc',
            new_name='desc',
        ),
    ]
